# Generated by Django 4.2.1 on 2023-06-01 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0002_rename_owner_account_owner_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="owner_id",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="expensecategory",
            old_name="owner_id",
            new_name="owner",
        ),
    ]
